; PlatformIO Project Configuration File
; INA228 Power Monitor with MQTT for Home Assistant
; Board: DFRobot FireBeetle ESP32-E

[env:firebeetle32]
platform = espressif32
board = firebeetle32
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.0
